feat(swaps): monitor pending payments before fail
ExchangeUnion/xud pull request #1822
Opened 2020-08-18 19:35 UTC by sangaman

This monitors all swap client payments until their resolution without putting deals into `SwapRecovery`. Previously, if a call to send payment failed but the payment was still in pending status (as has been the case with Connext), then we would fail the swap deal and monitor the payment in `SwapRecovery`. This had several downsides, namely:

1. Since the deal is marked as having failed in the database, if xud restarts while payment monitoring is ongoing, it won't resume monitoring because it sees the swap as having failed in the database. We only recover swaps that were "active" at the time xud shut down. See #1799.

2. When a deal is failed, the maker order it attempted to swap re-enters the order book and is available to be matched again. However, since the payment for the original deal is still pending, it may still go
through, meaning that the order can be "double filled" in such a case. See #1816.

By monitoring all pending payments to their resolution, we ensure that we don't fail deals that wind up completing.

Fixes #1799. Fixes #1816.

I'm putting this in draft state until I determine whether we need new or modified simulation tests to cover the new logic.

2020-08-19 09:46 UTC, erkarl reviewed
Code wise looks OK - will need to do more manual testing on this one.

2020-08-19 12:41 UTC, sangaman commented
> Code wise looks OK - will need to do more manual testing on this one.

Thanks, this should be good now. I tweaked the custom-xud patch for the instability and security simulation tests. And I added logic in `Swaps` to continuously retry settling an incoming payment if the first try fails when we are maker, since as maker we *need* to be able to claim those funds once we've gotten the preimage.

2020-08-19 12:54 UTC, kilrau commented
Great, but lets also leave this open for @raladev to test

2020-08-24 12:31 UTC, raladev requested changes
- [ ] I tested it with steps from #1799 issue but even after 15 mins after failed swaps (2 step in  1799 flow) i did not get Swap Recovery (is recovery messages on debug level?).  May be connecteed with connext errors on second srceen.

![Screenshot from 2020-08-24 14-57-32](https://user-images.githubusercontent.com/29906866/91044656-4d639280-e61e-11ea-8335-358ce12006c5.png)
![Screenshot from 2020-08-24 14-48-29](https://user-images.githubusercontent.com/29906866/91044658-4e94bf80-e61e-11ea-8cbe-eebcf203de48.png)

[maker_xud_log.log](https://github.com/ExchangeUnion/xud/files/5117752/maker_xud_log.log)
[connext_maker_.log](https://github.com/ExchangeUnion/xud/files/5117770/connext_maker_.log)
[taker_xud_log.log](https://github.com/ExchangeUnion/xud/files/5117753/taker_xud_log.log)

[xud-maker.log](https://github.com/ExchangeUnion/xud/files/5117751/xud-maker.log) - it is maker's xud DB, i just renamed it to .log ext

2020-08-25 16:32 UTC, sangaman commented
>     * [ ]  I tested it with steps from #1799 issue but even after 15 mins after failed swaps (2 step in  1799 flow) i did not get Swap Recovery (is recovery messages on debug level?).  May be connecteed with connext errors on second srceen.
> 
> 
> [Screenshot from 2020-08-24 14-57-32](https://user-images.githubusercontent.com/29906866/91044656-4d639280-e61e-11ea-8335-358ce12006c5.png)
> [Screenshot from 2020-08-24 14-48-29](https://user-images.githubusercontent.com/29906866/91044658-4e94bf80-e61e-11ea-8cbe-eebcf203de48.png)
> 
> [maker_xud_log.log](https://github.com/ExchangeUnion/xud/files/5117752/maker_xud_log.log)
> [connext_maker_.log](https://github.com/ExchangeUnion/xud/files/5117770/connext_maker_.log)
> [taker_xud_log.log](https://github.com/ExchangeUnion/xud/files/5117753/taker_xud_log.log)
> 
> [xud-maker-db.log](https://github.com/ExchangeUnion/xud/files/5117751/xud-maker.log) - it is maker's xud DB, i just renamed it to .log ext
> [xud-taker-db.log](https://github.com/ExchangeUnion/xud/files/5117804/xud-taker-db.log)

This looks like expected behavior - I'm not so familiar with the connext logs to say for sure but since we're no longer using swap recovery to monitor pending payments, the log messages you're used to aren't appearing. If you shut down and restarted xud, you should get the swap recovery messages as it would be recovering from a crash in such a case. The maker database doesn't show any swaps in the error state, but quite a few in the active state, which is good because xud will attempt to recover active swaps on start.

But this does raise a good point about logging, right now I don't really log anything when monitoring a pending swap payment. I can log an `info` message when monitoring begins and a `trace` each time we check on the pending payment. I'll update the PR with that logging.

2020-08-26 14:54 UTC, erkarl commented
I rebased this branch against master and simulated maker's connext payment erroring after 95 seconds:
```
26/08/2020 14:38:36.500 [P2P] debug: received swapRequest from 03a0c954dfe3404fa9d1c0074ec1f59b18452c7021d974aae58c994567d3427e28 (FrostSchool): {"proposedQuantity":1000000,"pairId":"BTC/USDT","orderId":"a0e5de90-e7a9-11ea-8a17-57cf4cf79eaf","rHash":"9b4641bef51d848a6ee6cc79034781b565705d272d473b9d88131def48fc02cd","takerCltvDelta":200}
26/08/2020 14:38:36.501 [ORDERBOOK] debug: added hold of 1000000 on order a0e5de90-e7a9-11ea-8a17-57cf4cf79eaf
26/08/2020 14:38:36.505 [SWAPS] debug: trying to accept deal: {"quantity":1000000,"localId":"a0e5de90-e7a9-11ea-8a17-57cf4cf79eaf","price":1,"isBuy":true} from xudPubKey: 03a0c954dfe3404fa9d1c0074ec1f59b18452c7021d974aae58c994567d3427e28
26/08/2020 14:38:36.505 [SWAPS] debug: New deal: {"rHash":"9b4641bef51d848a6ee6cc79034781b565705d272d473b9d88131def48fc02cd","pairId":"BTC/USDT","proposedQuantity":1000000,"orderId":"a0e5de90-e7a9-11ea-8a17-57cf4cf79eaf","price":1,"isBuy":true,"quantity":1000000,"makerAmount":1000000,"takerAmount":1000000,"makerCurrency":"BTC","takerCurrency":"USDT","makerUnits":1000000,"takerUnits":10000,"takerCltvDelta":200,"takerPubKey":"indra72Tqt1bPAZMc1KVnKNg8kFAs3MrkJTEgz9HJi8VzM9UBQKKyoH","destination":"indra72Tqt1bPAZMc1KVnKNg8kFAs3MrkJTEgz9HJi8VzM9UBQKKyoH","peerPubKey":"03a0c954dfe3404fa9d1c0074ec1f59b18452c7021d974aae58c994567d3427e28","localId":"a0e5de90-e7a9-11ea-8a17-57cf4cf79eaf","phase":0,"state":0,"role":1,"createTime":1598452716505}
26/08/2020 14:38:36.506 [SWAPS] debug: got USDT block height of 1
26/08/2020 14:38:36.506 [SWAPS] debug: found route to taker with total lock duration of 100 USDT blocks (~0h)
26/08/2020 14:38:36.507 [SWAPS] debug: calculated lock buffer for first leg: 22 BTC blocks (~4h)
26/08/2020 14:38:36.507 [SWAPS] debug: lock delta for final hop to maker: 166 BTC blocks (~28h)
26/08/2020 14:38:36.511 [LND-BTC] debug: added invoice of 1000000 for 9b4641bef51d848a6ee6cc79034781b565705d272d473b9d88131def48fc02cd with cltvExpiry 166
26/08/2020 14:38:36.513 [SWAPS] debug: Setting SwapAccepted phase for deal 9b4641bef51d848a6ee6cc79034781b565705d272d473b9d88131def48fc02cd
26/08/2020 14:38:36.514 [SWAPS] debug: sending swap accepted packet: {"rHash":"9b4641bef51d848a6ee6cc79034781b565705d272d473b9d88131def48fc02cd","makerCltvDelta":166,"quantity":1000000} to peer: 03a0c954dfe3404fa9d1c0074ec1f59b18452c7021d974aae58c994567d3427e28
26/08/2020 14:38:36.658 [LND-BTC] debug: accepted htlc for invoice 9b4641bef51d848a6ee6cc79034781b565705d272d473b9d88131def48fc02cd
26/08/2020 14:38:36.659 [SWAPS] debug: Executing maker code to resolve hash
26/08/2020 14:38:36.660 [SWAPS] debug: Setting SendingPayment phase for deal 9b4641bef51d848a6ee6cc79034781b565705d272d473b9d88131def48fc02cd
26/08/2020 14:38:36.665 [CONNEXT] debug: sending payment of 10000 with hash 0x9b4641bef51d848a6ee6cc79034781b565705d272d473b9d88131def48fc02cd to indra72Tqt1bPAZMc1KVnKNg8kFAs3MrkJTEgz9HJi8VzM9UBQKKyoH
26/08/2020 14:38:39.264 [LND-BTC] debug: new channel maximum outbound capacity: 12022517
26/08/2020 14:38:39.266 [LND-BTC] debug: new channel inbound capacity: 1644133
26/08/2020 14:38:39.267 [LND-BTC] debug: new channel total outbound capacity: 12022517
26/08/2020 14:40:05.670 [SWAPS] debug: sendPayment in resolveHash for swap 9b4641bef51d848a6ee6cc79034781b565705d272d473b9d88131def48fc02cd failed due to Timeout has occurred
26/08/2020 14:40:05.821 [CONNEXT] error: connext payment not found
26/08/2020 14:40:05.822 [SWAPS] debug: deal 9b4641bef51d848a6ee6cc79034781b565705d272d473b9d88131def48fc02cd failed in state Active & phase SendingPayment due to UnknownError (USDT): Timeout has occurred
26/08/2020 14:40:05.822 [SWAPS] warn: swap failed due to unknown error: Timeout has occurred
26/08/2020 14:40:05.823 [ORDERBOOK] debug: removed hold of 1000000 on order a0e5de90-e7a9-11ea-8a17-57cf4cf79eaf
26/08/2020 14:40:05.824 [SWAPS] debug: Sending UnknownError error to peer: {"rHash":"9b4641bef51d848a6ee6cc79034781b565705d272d473b9d88131def48fc02cd","failureReason":12,"errorMessage":"Timeout has occurred"}
26/08/2020 14:40:05.826 [SWAPS] error: could not resolve hash for deal 9b4641bef51d848a6ee6cc79034781b565705d272d473b9d88131def48fc02cd: 7.9 - Timeout has occurred
26/08/2020 14:40:11.674 [CONNEXT] error: connext server error 500: Internal Server Error
```

There are no `/hashlock-status` calls being made apart from 1 that happened before the connext payment failed.

Connext logs:
```
2020-08-26T14:38:36.272Z [CF-RpcRouter] Processed chan_getFreeBalanceState method in 10 ms
[1598452716667] INFO  (2780286 on arbuntu): received request
    url: "/hashlock-transfer"
    id: 693
    reqId: 693
[1598452716668] INFO  (2780286 on arbuntu): Getting client for publicIdentifier: indra8HMBrubZK9JzXjdH2tSbwu3FqukABKKXYqdx934E73sQs9XinN
[1598452719277] INFO  (2780286 on arbuntu): Getting client for publicIdentifier: indra8HMBrubZK9JzXjdH2tSbwu3FqukABKKXYqdx934E73sQs9XinN
2020-08-26T14:38:39.279Z [CF-GetFreeBalanceState] Executing with params: {"multisigAddress":"0x8c11..187d","assetId":"0x0000..0000"}
[1598452719282] INFO  (2780286 on arbuntu): Getting client for publicIdentifier: indra8HMBrubZK9JzXjdH2tSbwu3FqukABKKXYqdx934E73sQs9XinN
2020-08-26T14:38:39.284Z [CF-GetFreeBalanceState] Executing with params: {"multisigAddress":"0x8c11..187d","assetId":"0x61F6..C94D"}
2020-08-26T14:38:39.292Z [CF-GetFreeBalanceState] Before execution complete in 13 ms
2020-08-26T14:38:39.304Z [CF-GetFreeBalanceState] Before execution complete in 20 ms
2020-08-26T14:38:39.311Z [CF-GetFreeBalanceState] Executed method implementation in 19 ms
2020-08-26T14:38:39.312Z [CF-RpcRouter] Processed chan_getFreeBalanceState method in 33 ms
2020-08-26T14:38:39.314Z [CF-GetFreeBalanceState] Executed method implementation in 9 ms
2020-08-26T14:38:39.314Z [CF-RpcRouter] Processed chan_getFreeBalanceState method in 31 ms
[1598452722268] INFO  (2780286 on arbuntu): Getting client for publicIdentifier: indra8HMBrubZK9JzXjdH2tSbwu3FqukABKKXYqdx934E73sQs9XinN
2020-08-26T14:38:42.268Z [CF-GetFreeBalanceState] Executing with params: {"multisigAddress":"0x8c11..187d","assetId":"0x0000..0000"}
[1598452722270] INFO  (2780286 on arbuntu): Getting client for publicIdentifier: indra8HMBrubZK9JzXjdH2tSbwu3FqukABKKXYqdx934E73sQs9XinN
2020-08-26T14:38:42.271Z [CF-GetFreeBalanceState] Executing with params: {"multisigAddress":"0x8c11..187d","assetId":"0x61F6..C94D"}
2020-08-26T14:38:42.275Z [CF-GetFreeBalanceState] Before execution complete in 7 ms
2020-08-26T14:38:42.281Z [CF-GetFreeBalanceState] Before execution complete in 10 ms
2020-08-26T14:38:42.286Z [CF-GetFreeBalanceState] Executed method implementation in 8 ms
2020-08-26T14:38:42.286Z [CF-RpcRouter] Processed chan_getFreeBalanceState method in 18 ms
2020-08-26T14:38:42.288Z [CF-GetFreeBalanceState] Executed method implementation in 7 ms
2020-08-26T14:38:42.288Z [CF-RpcRouter] Processed chan_getFreeBalanceState method in 17 ms
[1598452725266] INFO  (2780286 on arbuntu): Getting client for publicIdentifier: indra8HMBrubZK9JzXjdH2tSbwu3FqukABKKXYqdx934E73sQs9XinN
2020-08-26T14:38:45.267Z [CF-GetFreeBalanceState] Executing with params: {"multisigAddress":"0x8c11..187d","assetId":"0x0000..0000"}
[1598452725268] INFO  (2780286 on arbuntu): Getting client for publicIdentifier: indra8HMBrubZK9JzXjdH2tSbwu3FqukABKKXYqdx934E73sQs9XinN
2020-08-26T14:38:45.269Z [CF-GetFreeBalanceState] Executing with params: {"multisigAddress":"0x8c11..187d","assetId":"0x61F6..C94D"}
2020-08-26T14:38:45.271Z [CF-GetFreeBalanceState] Before execution complete in 4 ms
2020-08-26T14:38:45.275Z [CF-GetFreeBalanceState] Before execution complete in 7 ms
2020-08-26T14:38:45.279Z [CF-GetFreeBalanceState] Executed method implementation in 7 ms
2020-08-26T14:38:45.279Z [CF-RpcRouter] Processed chan_getFreeBalanceState method in 13 ms
2020-08-26T14:38:45.280Z [CF-GetFreeBalanceState] Executed method implementation in 5 ms
2020-08-26T14:38 [...]

2020-08-26 15:21 UTC, sangaman commented
> I rebased this branch against master and simulated maker's connext payment erroring after 95 seconds:
> 
> There are no `/hashlock-status` calls being made apart from 1 that happened before the connext payment failed.

This pertains to #1708.

I think this is the expected behavior. It gets back a `26/08/2020 14:40:05.821 [CONNEXT] error: connext payment not found` on the first attempt to look up the payment. Since the payment isn't found, it goes on and fails the deal. Does that make sense to you?

2020-08-26 15:24 UTC, erkarl commented
> > I rebased this branch against master and simulated maker's connext payment erroring after 95 seconds:
> > There are no `/hashlock-status` calls being made apart from 1 that happened before the connext payment failed.
> 
> This pertains to #1708.
> 
> I think this is the expected behavior. It gets back a `26/08/2020 14:40:05.821 [CONNEXT] error: connext payment not found` on the first attempt to look up the payment. Since the payment isn't found, it goes on and fails the deal. Does that make sense to you?

Sorry, should have been more clear. It failed the deal, but the incoming BTC invoice is still up. It should cancel it, right?

2020-08-26 15:48 UTC, sangaman commented
> Sorry, should have been more clear. It failed the deal, but the incoming BTC invoice is still up. It should cancel it, right?

Got it, can you try again? I found another flaw with the logic in `failDeal` on when it removes existing invoices for the maker in `SendPayment` phase (which should be always now, because we're only failing deals where the payment has truly, permanently failed).

2020-08-26 15:55 UTC, erkarl commented
> > Sorry, should have been more clear. It failed the deal, but the incoming BTC invoice is still up. It should cancel it, right?
> 
> Got it, can you try again? I found another flaw with the logic in `failDeal` on when it removes existing invoices for the maker in `SendPayment` phase (which should be always now, because we're only failing deals where the payment has truly, permanently failed).

Yup, seems to work now. Did we move logging of cancelling invoices to a lower level?

2020-08-26 16:02 UTC, sangaman commented
> Yup, seems to work now. Did we move logging of cancelling invoices to a lower level?

It should still be at debug, `this.logger.debug(`canceled invoice for ${rHash}`);`

2020-08-26 17:34 UTC, sangaman commented
I rebased this branch on master to get some connext related fixes for testing purposes.

2020-08-26 18:52 UTC, raladev commented
- [ ] tested again with flow from #1799 and i again got peding htlcs with unblocked ETH payment. A also tried restart after some time, but there was no restore flow (because all swaps were marked as failed).

[Screenshot from 2020-08-26 21-40-07](https://user-images.githubusercontent.com/29906866/91343185-ce6c8680-e7e4-11ea-9555-9193d3bca9ef.png)
[Screenshot from 2020-08-26 21-38-13](https://user-images.githubusercontent.com/29906866/91343191-d0364a00-e7e4-11ea-862c-97c76a1b38de.png)
[Screenshot from 2020-08-26 21-26-59](https://user-images.githubusercontent.com/29906866/91343193-d0cee080-e7e4-11ea-825d-01a3451e746e.png)

Logs with trace level:

**Time of order placing as a taker 26/08/2020 18:20:57.841**

[simnet_connext_maker_pending.log](https://github.com/ExchangeUnion/xud/files/5131712/simnet_connext_pending.log)
[simnet_xud_maker_pending.log](https://github.com/ExchangeUnion/xud/files/5131713/simnet_xud_pending.log)

2020-08-26 19:06 UTC, sangaman commented
>     * [ ]  tested again with flow from #1799 and i again got peding htlcs with unblocked ETH payment. A also tried restart after some time, but there was no restore flow (because all swaps were marked as failed).
> 
> 
> [Screenshot from 2020-08-26 21-40-07](https://user-images.githubusercontent.com/29906866/91343185-ce6c8680-e7e4-11ea-9555-9193d3bca9ef.png)
> [Screenshot from 2020-08-26 21-38-13](https://user-images.githubusercontent.com/29906866/91343191-d0364a00-e7e4-11ea-862c-97c76a1b38de.png)
> [Screenshot from 2020-08-26 21-26-59](https://user-images.githubusercontent.com/29906866/91343193-d0cee080-e7e4-11ea-825d-01a3451e746e.png)
> 
> Logs with trace level:
> 
> **Time of order placing as a taker 26/08/2020 18:20:57.841**
> 
> [simnet_connext_maker_pending.log](https://github.com/ExchangeUnion/xud/files/5131712/simnet_connext_pending.log)
> [simnet_xud_maker_pending.log](https://github.com/ExchangeUnion/xud/files/5131713/simnet_xud_pending.log)
> 
> [simnet_connext_taker_pending.log](https://github.com/ExchangeUnion/xud/files/5131719/simnet_connext_taker_pending.log)
> [simnet_xud_taker_pending.log](https://github.com/ExchangeUnion/xud/files/5131720/simnet_xud_taker_pending.log)

This still seems like the intended behavior. It's hard to tell what's going on with Connext, but the payment is failing (as intended for testing purposes) and then the `/hashlock-status` calls to check on the payment aren't giving us a resolution, so we begin monitoring those payments on an interval.

```
26/08/2020 18:20:31.599 [SWAPS] [34mdebug[39m: sendPayment in resolveHash for swap dcf85025c51e734d10b645502f8d973239017fbdc3cab0399fa28c069024e521 failed due to connext server error 500: Internal Server Error
26/08/2020 18:20:31.601 [CONNEXT] [35mtrace[39m: sending request to /hashlock-status/0xdcf85025c51e734d10b645502f8d973239017fbdc3cab0399fa28c069024e521/0x0000000000000000000000000000000000000000
26/08/2020 18:20:31.703 [SWAPS] [32minfo[39m: started monitoring pending payment for swap dcf85025c51e734d10b645502f8d973239017fbdc3cab0399fa28c069024e521, will check every 300000 seconds
```

Later we see one of the scheduled attempts to check on the payment again, but presumably it's still pending.

```
26/08/2020 18:25:31.705 [SWAPS] [35mtrace[39m: checking pending payment status for swap dcf85025c51e734d10b645502f8d973239017fbdc3cab0399fa28c069024e521
26/08/2020 18:25:31.706 [CONNEXT] [35mtrace[39m: sending request to /hashlock-status/0xdcf85025c51e734d10b645502f8d973239017fbdc3cab0399fa28c069024e521/0x0000000000000000000000000000000000000000
```

The one thing I feel like the logs are missing (on trace level) is the result of the lookupPayment/hashlock-status calls, those simply aren't being printed anywhere. I also need to fix the logging that says "will check every 300000 seconds" instead of "will check every 300 seconds," and look into the simulation test case.

But the overall behavior above looks correct to me, given that the connext payments appear to be pending. As long as they're pending, we want to keep the incoming HTLCs alive. That's in contrast to Karl's tests where the payment fails permanently right away (and is confirmed by the `/hashlock-status` call which does not find any payment).

2020-08-26 19:12 UTC, raladev commented
```
But the overall behavior above looks correct to me, given that the connext payments appear to be pending. As long as they're pending, we want to keep the incoming HTLCs alive
```
connext payment in pending means that my balance in hold by connext node, but my ETH balance is free to use (first screen - maker has 9 ETH of 10) after failed swap. Maybe i just missed something in connext conception, but if my ETH is not blocked after failed swap it looks like should release BTC htlcs of counterparty.

2020-08-26 20:18 UTC, erkarl commented
> Maybe i just missed something in connext conception, but if my ETH is not blocked after failed swap it looks like I should release BTC htlcs of counterparty.

How did you make the connext payment fail? Can you check the status of your connext payment manually in your testing setup?
```
docker exec -it mainnet_connext_1 bash
curl -H 'Content-Type: application/json' http://0.0.0.0:5040/hashlock-status/0xPAYMENT_HASH/0x0000000000000000000000000000000000000000
```

2020-08-26 20:23 UTC, sangaman commented
I pushed the logging changes, the failing simulation test passed for me locally so I'm going to try restarting on Github Actions.

> ```
> But the overall behavior above looks correct to me, given that the connext payments appear to be pending. As long as they're pending, we want to keep the incoming HTLCs alive
> ```
> 
> connext payment in pending means that my balance in hold by connext node, but my ETH balance is free to use (first screen - maker has 9 ETH of 10 after failed 8 failed swaps and 1 successful). Maybe i just missed something in connext conception, but if my ETH is not blocked after failed swap it looks like I should release BTC htlcs of counterparty.
> 
> Otherwise as a result i may get forceclosed channel (as a taker in our case) because of expired pending htlcs after some time.
> Will check it tomorrow morning.

I wonder then if this is some issue with Connext not returning the correct status, but it appears as though Connext is telling us the payments are still pending. I can see the `hashlock-status` calls in the connext log although it's not printing the response. I'll also have xud log the raw hashlock status we get back from connext just for good measure in case you want to run your test case again. Thanks a lot.

2020-08-26 20:27 UTC, erkarl commented
> I wonder then if this is some issue with Connext not returning the correct status, but it appears as though Connext is telling us the payments are still pending. I can see the `hashlock-status` calls in the connext log although it's not printing the response. I'll also have xud log the raw hashlock status we get back from connext just for good measure in case you want to run your test case again. Thanks a lot.

That was my first thought as well. Let's wait for @raladev to manually check the status of the transfer in his testing setup. I believe the transfer app was only installed on the sender side as app proposal. If that's the case that `/hashlock-status` response will not have `expiry` and `status` field.

2020-08-26 20:51 UTC, sangaman commented
> If that's the case that `/hashlock-status` response will not have `expiry` and `status` field.

Aha this may be the issue then. ConnextClient treats a response with no `status` field as pending. Should we treat that as failed instead? The logic is below:

```typescript
      switch (transferStatusResponse.status) {
        case 'PENDING':
          return { state: PaymentState.Pending };
        case 'COMPLETED':
          return {
            state: PaymentState.Succeeded,
            preimage: transferStatusResponse.preImage?.slice(2),
          };
        case 'EXPIRED':
        case 'FAILED':
          return { state: PaymentState.Failed };
        default:
          return { state: PaymentState.Pending };
      }
```

This fix would be unrelated to the core change of this PR but I can include it in a separate commit.

2020-08-27 08:36 UTC, erkarl commented
> > If that's the case that `/hashlock-status` response will not have `expiry` and `status` field.
> 
> Aha this may be the issue then. ConnextClient treats a response with no `status` field as pending. Should we treat that as failed instead? The logic is below:
> 
> ```ts
>       switch (transferStatusResponse.status) {
>         case 'PENDING':
>           return { state: PaymentState.Pending };
>         case 'COMPLETED':
>           return {
>             state: PaymentState.Succeeded,
>             preimage: transferStatusResponse.preImage?.slice(2),
>           };
>         case 'EXPIRED':
>         case 'FAILED':
>           return { state: PaymentState.Failed };
>         default:
>           return { state: PaymentState.Pending };
>       }
> ```
> 
> This fix would be unrelated to the core change of this PR but I can include it in a separate commit.

Ideally, connext would not get into this state very often. I'm interested in confirming that it's the case in @raladev's testing setup. 

If we get a transfer status response that does not have a status field the correct behaviour would probably be to call `client.rejectInstallApp(appIdentityHash)` (available via rest-api-client `/reject-install`) to remove the app install proposal. Afterwards, the node should respond with 404 to the transfer status request.

2020-08-27 10:15 UTC, raladev commented
[again_pending_maker.log](https://github.com/ExchangeUnion/xud/files/5135733/again_pending_maker.log)
[again_pending_taker.log](https://github.com/ExchangeUnion/xud/files/5135735/again_pending_taker.log)

Maker's side:
```
bash-5.0# curl -H 'Content-Type: application/json' http://0.0.0.0:5040/hashlock-status/0xdcf85025c51e734d10b645502f8d973239017fbdc3cab0399fa28c069024e521/0x0000000000000000000000000000000000000000

{"senderIdentifier":"indra5eDcn7EpyfviCXgg4tnHDDZpb9gF8eoWRWJjjtcMbt7CHjRtqV","receiverIdentifier":"indra7kxQ9nZUDQ6L8hpNouP6n7XkL9XRanzHKZXDYuCWk8DBWh72cw","assetId":"0x0000000000000000000000000000000000000000","amount":"1000000000000000000","lockHash":"0xdcf85025c51e734d10

```
Taker's side:

```
bash-5.0# curl -H 'Content-Type: application/json' http://0.0.0.0:5040/hashlock-status/0xdcf85025c51e734d10b645502f8d973239017fbdc3cab0399fa28c069024e521/0x0000000000000000000000000000000000000000

{"message":"No HashLock Transfer found for lockHash: 0xdcf85025c51e734d10b645502f8d973239017fbdc3cab0399fa28c069024e521 and assetId: 0x0000000000000000000000000000000000000000"}bash-5.0# 
```

2020-08-27 13:08 UTC, sangaman commented
> [again_pending_maker.log](https://github.com/ExchangeUnion/xud/files/5135733/again_pending_maker.log)
> [again_pending_taker.log](https://github.com/ExchangeUnion/xud/files/5135735/again_pending_taker.log)
> 
> Maker's side:
> 
> ```
> bash-5.0# curl -H 'Content-Type: application/json' http://0.0.0.0:5040/hashlock-status/0x901a832ea49789bad0e4eae4fdbf165c8bee3ab3ff0d02a80fb0e15651929187/0x0000000000000000000000000000000000000000
> 
> {"senderIdentifier":"indra5eDcn7EpyfviCXgg4tnHDDZpb9gF8eoWRWJjjtcMbt7CHjRtqV","receiverIdentifier":"indra7kxQ9nZUDQ6L8hpNouP6n7XkL9XRanzHKZXDYuCWk8DBWh72cw","assetId":"0x0000000000000000000000000000000000000000","amount":"500000000000000000","lockHash":"0x901a832ea49789bad0e4eae4fdbf165c8bee3ab3ff0d02a80fb0e15651929187","expiry":"95686"}
> ```
> 
> Taker's side:
> 
> ```
> curl -H 'Content-Type: application/json' http://0.0.0.0:5040/hashlock-status/0x901a832ea49789bad0e4eae4fdbf165c8bee3ab3ff0d02a80fb0e15651929187/0x0000000000000000000000000000000000000000
> 
> {"message":"No HashLock Transfer found for lockHash: 0x901a832ea49789bad0e4eae4fdbf165c8bee3ab3ff0d02a80fb0e15651929187 and assetId: 0x0000000000000000000000000000000000000000"}bash-5.0# 
> 
> bash-5.0# 
> ```

Thanks for manually querying the hashlock status. It looks like we need to handle this response. Do you happen to know if the HTTP status code on the response was 200 or 404?

2020-08-27 13:21 UTC, sangaman commented
We confirmed the response above is a 404. The new logging statements I added are printing this:

```
27/08/2020 10:04:33.427 [CONNEXT] trace: hashlock status for payment with hash fa90360635b77281dc7a69ee087566ca6139dc99acf17173488ef30025677e01 is undefined
```

So in spite of the 404 we're getting to the switch statement I copied above and then treating `undefined` as pending by default, which is why xud is treating the payment as pending forever. I'll fix this in a separate commit (since it's not related to the original commit which is generic to all swaps and has no connext-specific changes), then we can give this branch one more test run and merge. Thanks for all the testing!

2020-08-27 14:11 UTC, raladev commented
Hash of fresh payment: 0x901a832ea49789bad0e4eae4fdbf165c8bee3ab3ff0d02a80fb0e15651929187
@sangaman try to read logs for this hash (https://github.com/ExchangeUnion/xud/pull/1822#issuecomment-681858906)

2020-08-27 14:59 UTC, sangaman commented
> Hash of fresh payment: 0x901a832ea49789bad0e4eae4fdbf165c8bee3ab3ff0d02a80fb0e15651929187
> @sangaman try to read logs for this hash ([#1822 (comment)](https://github.com/ExchangeUnion/xud/pull/1822#issuecomment-681858906))

Same thing here:

```
27/08/2020 10:04:57.540 [SWAPS] debug: sendPayment in resolveHash for swap 901a832ea49789bad0e4eae4fdbf165c8bee3ab3ff0d02a80fb0e15651929187 failed due to connext server error 500: Internal Server Error
27/08/2020 10:04:57.541 [CONNEXT] trace: sending request to /hashlock-status/0x901a832ea49789bad0e4eae4fdbf165c8bee3ab3ff0d02a80fb0e15651929187/0x0000000000000000000000000000000000000000
27/08/2020 10:04:57.630 [CONNEXT] trace: hashlock status for payment with hash 901a832ea49789bad0e4eae4fdbf165c8bee3ab3ff0d02a80fb0e15651929187 is undefined
```

Still getting `undefined` for the status, but not throwing the `PAYMENT_NOT_FOUND` error that we would expect with a 404 response, as Karl had tested above.

I'm going to push a commit with extremely explicit logging of all connext responses (just for purposes of testing this weird case) so we know what's going on and what change we need to make.

2020-08-27 15:19 UTC, erkarl commented
I'm looking at the code and we're definitely processing the status code first. So, in the case of 404 we don't care about the response body: https://github.com/ExchangeUnion/xud/blob/master/lib/connextclient/ConnextClient.ts#L725-L736

2020-08-27 15:34 UTC, erkarl commented
@raladev can you try again with the extra logging that @sangaman added?

2020-08-27 15:53 UTC, raladev commented
[extend_connext_maker.log](https://github.com/ExchangeUnion/xud/files/5137439/extend_connext_maker.log)
[log_maker_extend_xud.log](https://github.com/ExchangeUnion/xud/files/5137440/log_maker_extend_xud.log)
[log_taker_extend_xud.log](https://github.com/ExchangeUnion/xud/files/5137441/log_taker_extend_xud.log)

200 code

also i checked manually - 200 for maker and 404 for taker.

![Screenshot from 2020-08-27 18-51-43](https://user-images.githubusercontent.com/29906866/91465568-9a519e00-e896-11ea-9887-ee39a445be66.png)

2020-08-27 16:25 UTC, erkarl approved these changes

2020-08-27 20:00 UTC, kilrau commented
Security test keep failing. Please check this out @sangaman , after this is merged we just discussed to tag `rc.2` from master.

2020-08-28 07:24 UTC, erkarl commented
Could it be that it's a legit failure @sangaman:
```
     --- FAIL: TestSecurityUnsettledChannels/taker_stalling_after_2nd_htlc (141.65s)
        tests-security.go:460: 
            	Error Trace:	tests-security.go:460
            	            				harnessTest.go:95
            	            				xud_test.go:269
            	Error:      	"0" is not greater than "20000"
            	Test:       	TestSecurityUnsettledChannels/taker_stalling_after_2nd_htlc
FAIL
exit status 1
```

2020-08-28 08:54 UTC, raladev approved these changes

2020-08-28 18:35 UTC, raladev approved these changes

2020-08-28 18:35 UTC, merged