fix: don't activate unsupported pairs with peers
ExchangeUnion/xud pull request #1884
Opened 2020-09-10 06:00 UTC by sangaman

This ensures that, even when not running in strict mode, we only activate trading pairs with peers when we support both currencies of the pair locally. Previously we would activate every trading pair, like
BTC/LTC when we don't have a swap client for LTC, resulting in us requesting and receiving order updates for trading pairs that are irrelevent to us.

Related https://github.com/ExchangeUnion/xud/pull/1864#issuecomment-687140868:

> after adding new pair, the peer with new pair sends packet update to his peers. And after that these peers send GetOrders packet to this peer even if they have no this pair. It would be good to not ask orders if we have no this new pair.

2020-09-10 12:55 UTC, rsercano commented
> This ensures that, even when not running in strict mode, we only activate trading pairs with peers when we support both currencies of the pair locally. Previously we would activate every trading pair, like
> BTC/LTC when we don't have a swap client for LTC, resulting in us requesting and receiving order updates for trading pairs that are irrelevent to us.
> 
> Related [#1864 (comment)](https://github.com/ExchangeUnion/xud/pull/1864#issuecomment-687140868):
> 
> > after adding new pair, the peer with new pair sends packet update to his peers. And after that these peers send GetOrders packet to this peer even if they have no this pair. It would be good to not ask orders if we have no this new pair.

That's a more intuitive way than the first try that I made, but why don't we return just a simple `bool` for `has` method?

2020-09-10 13:18 UTC, sangaman commented
> That's a more intuitive way than the first try that I made, but why don't we return just a simple bool for has method?

Good catch, this was just an oversight. I meant to change it to a bool (copied from the `get`) method but just missed it. I'll update the PR.

2020-09-10 14:44 UTC, raladev commented
- [ ] still see GetOrders packet
![Screenshot from 2020-09-10 17-42-27](https://user-images.githubusercontent.com/29906866/92747751-326a7f80-f38d-11ea-9b5f-3123d873da18.png)
![Screenshot from 2020-09-10 17-41-35](https://user-images.githubusercontent.com/29906866/92747755-33031600-f38d-11ea-917d-fd931342c7dc.png)

2020-09-10 14:44 UTC, raladev requested changes
Above

2020-09-11 06:19 UTC, sangaman commented
>     * [ ]  still see GetOrders packet

Is the issue here that you're sending a GetOrders packet for USDT/BTC when locally you only support BTC/USDT? That actually looks like a slightly different issue from what I originally set out to fix, but it would make sense to fix that as well. Here we support both currencies of the trading pair but we don't actually support the trading pair itself, which does not seem to be a situation that's currently handled properly by the code. I'll push a fix in a separate commit.

2020-09-11 06:23 UTC, sangaman commented
I actually went ahead and amended the existing commit since it's so closely related. @raladev could you please try this branch again and see if you're sending the expected `GetOrders` packets? Thanks.

2020-09-11 11:07 UTC, raladev approved these changes

2020-09-11 13:10 UTC, sangaman commented
I fixed the tests (that were expecting even the currencies we don't locally support to get activated), could you review one more time real quick @raladev?

2020-09-11 14:32 UTC, raladev approved these changes

2020-09-11 18:02 UTC, merged