(WIP) fix: handling insufficient balance errors for swap clients
ExchangeUnion/xud pull request #1908
Opened 2020-09-20 06:31 UTC by rsercano

attempts to resolve #1558 

This's a WIP (Work in Progress) PR, I'm currently having trouble with my local setup and @raladev is helping me with it, apart from that please let me know what else actually need to be done.

I suppose matched orders should return to the orderbook? @kilrau (I couldn't test this yet too)

@sangaman @raladev @kilrau

2020-09-20 16:33 UTC, kilrau commented
> I suppose matched orders should return to the orderbook? @kilrau (I couldn't test this yet too)

Not clear what you mean here, could you rephrase?

2020-09-21 05:54 UTC, rsercano commented
> > I suppose matched orders should return to the orderbook? @kilrau (I couldn't test this yet too)
> 
> Not clear what you mean here, could you rephrase?

I mean, currently if we get unexpectedclienterror due to insufficient balance, maker orders are being removed?

2020-09-21 07:02 UTC, rsercano commented
**EDIT:** nvm @kilrau, thanks to @raladev I managed to test this locally, seems to be working, could you please test and let me know?
@raladev @kilrau @sangaman 

![image](https://user-images.githubusercontent.com/3640368/93739683-8b3de180-fbf1-11ea-9e6c-94910f720bc1.png)

2020-09-22 07:28 UTC, sangaman requested changes

2020-09-22 07:28 UTC, sangaman commented on lib/swaps/Swaps.ts
> +      if (err.message?.includes('insufficient local balance')) {
This is an lnd specific message so it should detected and handled within the LndClient class in the `getRoute` method. I think ideally the LndClient will throw a specific error type (you can add it to swaps/errors.ts) indicating that there's insufficient balance, and then that error should be checked for here. That way Connext/other swap clients can throw the same error later on.

2020-09-22 07:28 UTC, sangaman commented on lib/swaps/Swaps.ts
> +        failureReason: (err.message?.includes('insufficient local balance')) ?
Same thing here, `getRoute` should throw an error indicating insufficient balance, and then we check for that error here when setting the failure reason.

2020-09-22 10:11 UTC, rsercano commented
Would you please recheck? @sangaman

2020-09-24 13:04 UTC, raladev approved these changes

2020-09-24 16:45 UTC, sangaman approved these changes
New approach looks good. I'm thinking it might make sense to refactor a bit since ConnextClient has it's own error for insufficient balance and, but that isn't particularly important here, just a thought for down the road. Thanks!

2020-09-24 16:46 UTC, merged