feat: derive child seed for swap clients
ExchangeUnion/xud pull request #1928
Opened 2020-10-09 08:40 UTC by sangaman

This change uses separate mnemonics and seeds for each swap client that are unique to that client, rather than using a single seed and mnemonic across all clients. To accomplish this, a new method is added to the seedutil tool to derive a child mnemonic from a provided mnemonic. This is done by extracting the 16 bytes of entropy from the provided seed, concatenating the entropy with the name of the client (e.g. "LND-BTC") and then hashing the concatenation and taking 16 bytes from the resulting hash.

Closes #1576.

2020-10-09 10:34 UTC, raladev commented
- [ ] xud is crashed on start
```
[webproxy]
disable = true
port = 8080
[xud-backup] Waiting for backup_dir value
Oct 09 10:32:27.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module 'lib/utils/seedutil'
Require stack:
- /app/dist/lndclient/LndClient.js
- /app/dist/swaps/SwapClientManager.js
- /app/dist/Xud.js
- /app/bin/xud
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/app/dist/lndclient/LndClient.js:48:20)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/dist/lndclient/LndClient.js',
    '/app/dist/swaps/SwapClientManager.js',
    '/app/dist/Xud.js',
    '/app/bin/xud'
  ]
}
```

2020-10-09 10:34 UTC, raladev requested changes
Above

2020-10-09 14:25 UTC, erkarl commented
> xud is crashed on start

Getting the same output as above.

2020-10-09 14:53 UTC, sangaman commented
I think the crash had to do with `Error: Cannot find module 'lib/utils/seedutil'` - importing as `lib/utils/seedutil` instead of `../utils/seedutil` doesn't work for reasons I don't fully understand, but vscode automatically uses the former when generating imports occasionally. It should work now.

I also had to tweak the seedutil test case to ensure the deciphered seed doesn't change between runs, since the child mnemonic will change each time it is derived due to the salt being different.

2020-10-09 17:20 UTC, sangaman commented
I added a test case for deriving a child seed for an aezeed with a password.

2020-10-12 11:21 UTC, raladev approved these changes

2020-10-13 13:47 UTC, erkarl approved these changes

2020-10-13 13:48 UTC, merged