fix: openchannel assertion error for string amount (#1643)
ExchangeUnion/xud pull request #1950
Opened 2020-10-21 11:59 UTC by rsercano

resolves #1643

2020-10-22 12:02 UTC, raladev requested changes
- openchannel fix works fine
-  [ ] but it would be good to handle this assertion for all commands, usually it appears when u use string instead of number for required parameter, I found only two commands - buy/sell
![Screenshot from 2020-10-22 14-35-24](https://user-images.githubusercontent.com/29906866/96869019-90ec4880-1477-11eb-9bff-3c9c206cde87.png)

2020-10-22 13:06 UTC, rsercano commented
I commented on the linked issue, do you want me to write a generic error catching mechanism for this or just controlling the case @raladev mentioned for the known commands ? @sangaman

2020-10-27 13:00 UTC, raladev approved these changes

2020-11-01 21:35 UTC, sangaman approved these changes
I think a generic args checker would be a great idea, but this simple fix works for now. Thanks.

2020-11-01 21:36 UTC, merged