fix: manual ban causes an undefined log entry (#1779)
ExchangeUnion/xud pull request #1951
Opened 2020-10-21 12:07 UTC by rsercano

resolves #1779

2020-10-21 17:05 UTC, raladev commented
- [ ] got different ban message (not `node ${nodePubKey} was banned manually`)
```
21/10/2020 17:02:54.880 [RPC] trace: received call /xudrpc.Xud/Ban
21/10/2020 17:02:54.889 [DB] trace: Executing (default): SELECT `id`, `event`, `nodeId`, `createdAt` FROM `reputationEvents` AS `ReputationEvent` WHERE `ReputationEvent`.`nodeId` = 1 ORDER BY `ReputationEvent`.`createdAt` DESC;
21/10/2020 17:02:54.893 [DB] trace: Executing (default): UPDATE `nodes` SET `banned`=$1,`updatedAt`=$2 WHERE `id` = $3
21/10/2020 17:02:54.897 [P2P] info: node 03ece33a30db1dbce4b62fa96a5e9541138a24997ef5672eebed2d332270e39542 was banned due to ManualBan
21/10/2020 17:02:54.897 [P2P] debug: Peer 03ece33a30db1dbce4b62fa96a5e9541138a24997ef5672eebed2d332270e39542 (OzoneYellow): closing socket. reason: Banned
```

2020-10-21 17:07 UTC, raladev requested changes
above

2020-10-23 06:42 UTC, rsercano commented
In my case it was empty @raladev, but I added the `ManualBan` check too.

2020-10-26 11:13 UTC, raladev approved these changes

2020-10-27 08:15 UTC, sangaman approved these changes

2020-10-27 08:15 UTC, merged