fix: changes removeorder output to a more meaningful message (#1526)
ExchangeUnion/xud pull request #1986
Opened 2020-11-10 14:28 UTC by rsercano

resolves #1526

2020-11-10 14:41 UTC, erkarl submitted a review, later dismissed

2020-11-10 15:05 UTC, raladev submitted a review, later dismissed

2020-11-11 05:37 UTC, sangaman requested changes
See below about how we're calculating remaining quantity, otherwise this looks good to me.

2020-11-11 05:37 UTC, sangaman commented on lib/orderbook/OrderBook.ts
> +      remainingQuantity: remainingFromOrder > onHoldQuantity ? remainingFromOrder : 0,
This seems off to me. If we're trying to indicate the quantity that will remain on the order after any holds or complete, I figure it should be:

```typescript
const remainingQuantity = orderQuantity - removedQuantity - remainingQuantityToRemove;
```

Or perhaps simpler we just use the current quantity on the order (after we've removed whatever we were able to before holds) in which case I don't think we need the `orderQuantity` variable at all.

```typescript
const remainingQuantity = order.quantity - remainingQuantityToRemove;
```

2020-11-16 11:28 UTC, raladev approved these changes

2020-11-17 07:29 UTC, erkarl approved these changes

2020-11-17 07:30 UTC, erkarl commented
@sangaman can we get this in?

2020-11-18 06:34 UTC, sangaman approved these changes
Looks good with my last feedback addressed, thanks.

2020-11-18 08:58 UTC, merged