feat: enhance simulation test README
ExchangeUnion/xud pull request #2001
Opened 2020-11-23 09:51 UTC by kilrau

Closes https://github.com/ExchangeUnion/xud/issues/1995

2020-11-23 18:08 UTC, erkarl requested changes

2020-11-23 18:08 UTC, erkarl commented on test/simulation/README.md
> +npm run test:sim:clean
```suggestion
npm run test:sim:clean
npm run test:sim:clean:indra
```

2020-11-24 15:00 UTC, sangaman reviewed
A couple of comments, also one minor style nit for readability purposes would be to have a line of whitespace between the text and ``` blocks of code.

2020-11-24 15:34 UTC, kilrau commented on test/simulation/README.md
> +npm install -g typescript
Not sure, added it because of https://github.com/ExchangeUnion/xud/issues/1995#issuecomment-729935733 and I believe it fixed a ts error I got once.

2020-11-24 15:34 UTC, kilrau commented on test/simulation/README.md
> +rm -rf ./test/simulation/temp
Moved to the second part.

2020-11-24 15:43 UTC, kilrau commented
But more importantly: can you get the tests to pass locally now? @sangaman Honestly, the time Moshe and I invested here was mainly to find steps and a environment (versions) for tests to pass for you.

@erkarl @michael1011 @moshababo and I can get tests to pass reliably by now.

2020-11-25 07:23 UTC, LePremierHomme commented on test/simulation/README.md
> +npm install -g typescript
I later verified that indeed it's not required if you run `npm install` (which you must do anyway).
See here: https://github.com/ExchangeUnion/xud/issues/1995#issuecomment-730682984

2020-11-25 09:46 UTC, erkarl approved these changes

2020-11-25 09:51 UTC, kilrau commented
Well I guess Daniel will let us know if tests still don't work for him.

2020-11-25 09:51 UTC, merged

2020-11-27 19:20 UTC, sangaman commented
> Well I guess Daniel will let us know if tests still don't work for him.

Still no, unfortunately, tried all the steps here and am getting the same old:

```
2020/11/27 19:18:52 cannot start xud network: timeout waiting for TLS cert file to be created after 20 seconds: /app/temp/xuddatadir-Dave/tls.cert
exit status 1
```