feat: change master password
ExchangeUnion/xud pull request #2007
Opened 2020-11-26 09:15 UTC by sangaman

This adds the ability to change the master password of an existing xud node. Changing the password re-encrypts the node key on disk and queues password changes for all lnd wallets.

Lnd does not currently offer the ability to change the password of an unlocked, running instance. Instead lnd can only change its password right after being started while it is still locked. Xud therefore saves the old password for each lnd wallet to the xud database and encrypts the old password using the new passwords. On subsequent unlocks of xud, when we go to unlock lnd wallets we first check whether we have any old passwords in the database corresponding to any lnd wallets. If we do, we decrypt the old password and change the password for lnd, which in turn will unlock lnd.

Closes #1981.

Note that this also introduces a framework for tracking a database's version and migrating from one version to the next when the database schema needs to be modified. The migrations consist of an array of methods that each are responsible for upgrading from a particular version, and they are run in sequence when we detect that the current database version is lower than the latest version.

The xucli command is `changepass`.

2020-11-26 12:43 UTC, raladev requested changes
- [ ] `Enter a password:` change to `Enter new password:`
- [ ]  add sentence after password changing `lnd restart is required to Apply change to lnd`.
- [ ] it would be good to support conception of password changing -> Enter old password -> Enter new password -> Re-enter new password. I dont like the idea that anyone can change password without any additional data if node is unlocked (even if anyone can withdraw all crypto if node is unlocked :) ).
- suggestion: make wrapper on xud-docker side for changepass call that will restart lnds automatically;
- [ ] got err when tried to unlock the node after password changing + my lnd were not unlocked on xud unlock (I unlocked it manually using old password)

Steps:
1. `bash xud.sh -b pwd`
2. create wallet, wait for channels (if u have no, i used old env)
3. `changepass` ->set new pass
4. down (stop and remove all containers)
5. `bash xud.sh -b pwd` - start env again -> create new containers

utils output:
```
Enter master xud password: 
Error: 2 UNKNOWN: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length

Enter master xud password: 
xud is running and unlocked, try checking its status with 'xucli getinfo'

Enter master xud password: 
Ctr+C
simnet > status
┌─────────┬──────────────────────────────────────────────────┐
│ SERVICE │ STATUS                                           │
├─────────┼──────────────────────────────────────────────────┤
│ lndbtc  │ Wallet locked. Unlock with xucli unlock.         │
├─────────┼──────────────────────────────────────────────────┤
│ lndltc  │ Wallet locked. Unlock with xucli unlock.         │
├─────────┼──────────────────────────────────────────────────┤
│ connext │ Starting...                                      │
├─────────┼──────────────────────────────────────────────────┤
│ xud     │ Waiting for lndbtc, lndltc, connext              │
└─────────┴──────────────────────────────────────────────────┘
simnet > 

```

xud logs
```
26/11/2020 12:32:51.422 [RPC] error: call /xudrpc.Xud/GetInfo errored with code 12: xud is locked
26/11/2020 12:32:52.143 [RPC] error: call /xudrpc.Xud/GetInfo errored with code 12: xud is locked
26/11/2020 12:33:10.284 [RPC] error: call /xudrpc.XudInit/UnlockNode errored with code 3: password is incorrect
26/11/2020 12:33:14.296 [GLOBAL] info: Local nodePubKey is 0343722e976e24e2115199822316d99773e2d12b68c2d152e6b298490274fcee9a
26/11/2020 12:33:14.309 [RPC] error: call /xudrpc.XudInit/UnlockNode errored with code 2: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
26/11/2020 12:33:14.313 [P2P] info: Connecting to simnet XU network
26/11/2020 12:33:14.317 [P2P] info: p2p server listening on 0.0.0.0:28885
26/11/2020 12:33:14.318 [P2P] debug: Verifying reachability of advertised address: zd7v22z76zqemn3w6krjb6rb34chtrhbvqquabwixkhsubfwutciy4id.onion:28885
26/11/2020 12:33:14.336 [P2P] info: Connecting to known / previously connected peers
26/11/2020 12:33:14.337 [P2P] debug: creating new outbound socket connection to xud1.simnet.exchangeunion.com:28885
26/11/2020 12:33:14.339 [P2P] debug: creating new outbound socket connection to xud.kilrau.com:28885
```

lndbtc logs:
```
2020-11-26 12:32:48.111 [DBG] BTCN: Received headers (num 0) from 35.231.222.142:38555 (outbound)
2020-11-26 12:32:48.513 [DBG] BTCN: Received cfheaders (stop_hash=05060bf2ecd36d91fa5c6725083f0e2ebe22185218d5a860fdeac8002fd23373, num_filter_hashes=5) from 35.231.222.142:38555 (outbound)
2020-11-26 12:32:48.513 [DBG] BTCN: Writing filter headers up to height=219523, hash=05060bf2ecd36d91fa5c6725083f0e2ebe22185218d5a860fdeac8002fd23373, new_tip=9780b3ecd08b43c849b988f65a0dbb9ebfcd028a5c6f634a4d4bc20801f8d7eb
2020-11-26 12:33:23.851 [DBG] BTCN: Received inv (block 5168825a08e70a11da7298205c0214f94fb1483c46404d9c97c3860ce7f4e326) from 35.231.222.142:38555 (outbound)
2020-11-26 12:33:23.851 [DBG] BTCN: Sending getheaders (locator 05060bf2ecd36d91fa5c6725083f0e2ebe22185218d5a860fdeac8002fd23373, stop 5168825a08e70a11da7298205c0214f94fb1483c46404d9c97c3860ce7f4e326) to 35.231.222.142:38555 (outbound)
2020-11-26 12:33:24.066 [DBG] BTCN: Received headers (num 1) from 35.231.222.142:38555 (outbound)
2020-11-26 12:33:24.066 [INF] BTCN: Processed 6 blocks in the last 38.09s (height 219524, 2020-11-26 12:33:23 +0000 UTC)
2020-11-26 12:33:24.072 [DBG] BTCN: Sending getheaders (locator 5168825a08e70a11da7298205c0214f94fb1483c46404d9c97c3860ce7f4e326, stop 0000000000000000000000000000000000000000000000000000000000000000) to 35.231.222.142:38555 (outbound)
```

lnd unlocking:
```
simnet > lndbtc-lncli unlock
Input wallet password: (new xud password)
[lncli] rpc error: code = Unknown desc = invalid passphrase for master public key
simnet > lndbtc-lncli unlock
Input wallet password: (old xud password)

lnd successfully unlocked!
simnet > 
```

2020-11-26 14:43 UTC, kilrau commented
>  add sentence after password changing lnd restart is required to Apply change to lnd.

Not needed since lnd is in unlocked state in this moment and continues to be fully functioning. Next time the environment/lnd restarts, the new password is active, I don't see any reason to trigger a restart / ask the user to restart lnd (and this is probably also the reason why the lightning labs team decided not to do that on lnd).

> it would be good to support conception of password changing -> Enter old password -> Enter new password -> Re-enter new password. I dont like the idea that anyone can change password without any additional data if node is unlocked (even if anyone can withdraw all crypto if node is unlocked :) ).

Yep, agree (and lnd requires current password first too, it's convention):
```
lncli changepassword
Input current wallet password: 
Input new wallet password: 
Confirm new wallet password: 
```

> suggestion: make wrapper on xud-docker side for changepass call that will restart lnds automatically;

As i said above, don't think that's needed.

> got err when tried to unlock the node after password changing + my lnd were not unlocked on xud unlock (I unlocked it manually using old password)

2020-11-26 15:34 UTC, sangaman commented
>> add sentence after password changing lnd restart is required to Apply change to lnd.
>
> Not needed since lnd is in unlocked state in this moment and continues to be fully functioning. Next time the environment/lnd restarts, the new password is active, I don't see any reason to trigger a restart / ask the user to restart lnd (and this is probably also the reason why the lightning labs team decided not to do that on lnd).

This was more or less what I thought, since we're not expecting the user to be unlocking lnd manually I didn't think a message was necessary. I did think about possibly adding a message like "lnd passwords will be changed next time xud is unlocked" maybe, thoughts?

> it would be good to support conception of password changing -> Enter old password -> Enter new password -> Re-enter new password. I dont like the idea that anyone can change password without any additional data if node is unlocked (even if anyone can withdraw all crypto if node is unlocked :) ).

I skipped this step because the original password is already needed to unlock xud before changing the password is allowed, but I can add it in since both you and kilrau thought this.

I'm looking into why the lnd passwords weren't changed now.

2020-11-26 15:39 UTC, kilrau commented
> I did think about possibly adding a message like "lnd passwords will be changed next time xud is unlocked" maybe, thoughts?

:+1: 

> I skipped this step because the original password is already needed to unlock xud before changing the password is allowed, but I can add it in since both you and kilrau thought this.

Yes, for the sake of being in line with lnd and others

2020-11-27 05:43 UTC, sangaman commented
Feedback applied and the bug with changing lnd password was fixed, apparently taking the encrypted bytes and converting them to `utf8`, then back to bytes before decrypting doesn't work. But using `base64` does work. I'm storing the old password in the database as encrypted text, so now it's base64 text instead of utf8. Tested in my docker setup and lnd passwords change successfully.

Changing the password now requires the old password as well and a message of `passwords for lnd wallets will be changed the next time xud is restarted and unlocked` is printed in the cli after a successful password change,

2020-11-27 12:39 UTC, raladev commented
- [ ] i did not get new string - `passwords for lnd wallets will be changed the next time xud is restarted and unlocked`
```
simnet > changepass
You are changing the master password for xud and underlying wallets.
Enter old password: 
Enter new password: 
Re-enter password: 

success
```

- [ ] now, after password changing and restart my lnds have such status
```
 2 UNKNOWN: verification failed: signature mismatch after caveat verification
```
![Screenshot from 2020-11-27 15-35-06](https://user-images.githubusercontent.com/29906866/100450349-8bad9980-30c6-11eb-9003-d99b1d49bc0b.png)

xud logs:
```
27/11/2020 12:33:16.285 [LND-BTC] info: new status: Unlocked
27/11/2020 12:33:16.285 [LND-BTC] info: password changed & wallet unlocked
27/11/2020 12:33:16.318 [LND-LTC] info: new status: Unlocked
27/11/2020 12:33:16.318 [LND-LTC] info: password changed & wallet unlocked
27/11/2020 12:33:18.018 [CONNEXT] info: trying to verify connection to connext
27/11/2020 12:33:18.392 [CONNEXT] error: connext server error 500: Internal Server Error
27/11/2020 12:33:18.394 [CONNEXT] error: could not verify connection to connext, retrying in 5000 ms: 8.5 - connext server error 500: Internal Server Error
27/11/2020 12:33:18.840 [P2P] debug: Connected pre-handshake to 0364c3631630feb6def6a89f7c14ba76bc755572e4680e1518d5ff3819f3ee9268@ntnfdfyugluvt5eh2yhuftpuobfmkzhtnye7akhu32ahnophi3ddzsad.onion:28885
27/11/2020 12:33:19.021 [P2P] debug: Peer 0364c3631630feb6def6a89f7c14ba76bc755572e4680e1518d5ff3819f3ee9268@ntnfdfyugluvt5eh2yhuftpuobfmkzhtnye7akhu32ahnophi3ddzsad.onion:28885 session in-encryption enabled
27/11/2020 12:33:19.069 [P2P] debug: Peer 0364c3631630feb6def6a89f7c14ba76bc755572e4680e1518d5ff3819f3ee9268 (MessageNaive) session out-encryption enabled
27/11/2020 12:33:19.070 [P2P] verbose: opened connection to 0364c3631630feb6def6a89f7c14ba76bc755572e4680e1518d5ff3819f3ee9268 (MessageNaive) at ntnfdfyugluvt5eh2yhuftpuobfmkzhtnye7akhu32ahnophi3ddzsad.onion:28885
27/11/2020 12:33:19.383 [P2P] verbose: received 3 nodes (0 new) from 0364c3631630feb6def6a89f7c14ba76bc755572e4680e1518d5ff3819f3ee9268 (MessageNaive)
27/11/2020 12:33:20.088 [P2P] debug: received order bb5155b0-30ac-11eb-ac6b-c10519dd9b23 for deactivated trading pair
27/11/2020 12:33:20.089 [P2P] debug: received order bb51a3d0-30ac-11eb-ac6b-c10519dd9b23 for deactivated trading pair
27/11/2020 12:33:20.660 [LND-LTC] info: trying to verify connection to lnd at lndltc:10009
27/11/2020 12:33:20.660 [LND-BTC] info: trying to verify connection to lnd at lndbtc:10009
27/11/2020 12:33:20.666 [LND-BTC] error: could not verify connection at lndbtc:10009, error: {"code":2,"metadata":{"_internal_repr":{},"flags":0},"details":"verification failed: signature mismatch after caveat verification"}, retrying in 5000 ms
27/11/2020 12:33:20.669 [LND-LTC] error: could not verify connection at lndltc:10009, error: {"code":2,"metadata":{"_internal_repr":{},"flags":0},"details":"verification failed: signature mismatch after caveat verification"}, retrying in 5000 ms
Nov 27 12:33:22.000 [notice] Closed 1 streams for service [scrubbed].onion for reason resolve failed. Fetch status: No more HSDir available to query.
27/11/2020 12:33:22.525 [P2P] warn: could not open connection to outbound peer (025b2b4bfc5fef0bb164a60d29355828bffd4bf33378d88fbf5613f9397e3c5fea@u3bpgzigngvf4h37jk6ie2rv6ixvpsyppq57fwvs2zg6cagwzvuobxad.onion:28885): could not connect to peer at u3bpgzigngvf4h37jk6ie2rv6ixvpsyppq57fwvs2zg6cagwzvuobxad.onion:28885: Socks5 proxy rejected connection - HostUnreachable
27/11/2020 12:33:22.526 [P2P] debug: creating new outbound socket connection to u3bpgzigngvf4h37jk6ie2rv6ixvpsyppq57fwvs2zg6cagwzvuobxad.onion:28885
27/11/2020 12:33:23.289 [LND-BTC] error: getinfo error: Error: 2 UNKNOWN: verification failed: signature mismatch after caveat verification
    at Object.exports.createStatusError (/app/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/app/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/app/node_modules/grpc/src/client_interceptors.js:847:24)
27/11/2020 12:33:23.290 [LND-LTC] error: getinfo error: Error: 2 UNKNOWN: verification failed: signature mismatch after caveat verification
    at Object.exports.createStatusError (/app/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/app/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/app/node_modules/grpc/src/client_interceptors.js:847:24)
27/11/2020 12:33:23.294 [CONNEXT] error: connext server error 500: Internal Server Error
27/11/2020 12:33:23.357 [LND-BTC] error: getinfo error: Error: 2 UNKNOWN: verification failed: signature mismatch after caveat verification
    at Object.exports.createStatusError (/app/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/app/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/app/node_modules/grpc/src/client_interceptors.js:847:24)
27/11/2020 12:33:23.357 [LND-LTC] error: getinfo error: Error: 2 UNKNOWN: verification failed: signature mismatch after caveat verification
    at Object.exports.createStatusError (/app/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/app/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/app/node_modules/grpc/src/client_interceptors.js:847:24)
27/11/2020 12:33:23.360 [CONNEXT] error: connext server error 500: Internal Server Error
```
lndbtc logs (found nothing in it):
```
2020-11-27 12:33:16.338 [INF] LTND: Primary chain is set to: bitcoin
2020-11-27 12:33:17.012 [INF] LNWL: Opened wallet
2020-11-27 12:33:17.668 [INF] LNWL: The wallet has been unlocked without a time limit
2020-11-27 12:33:17.668 [INF] LTND: LightningWallet opened
2020-11-27 12:33:17.668 [DBG] LNWL: Birthday block has already been verified: height=215521, hash=0a8cb167f7ff20651ca82fba3348e1619cc92393bc9bce3fe9af39e8203ed339
2020-11-27 12:33:17.668 [DBG] LNWL: Waiting for chain backend to sync to tip
2020-11-27 12:33:17.671 [INF] SRVR: Proxying all network traffic via Tor (stream_isolation=true)! NOTE: Ensure the backend node is proxying over Tor as well
2020-11-27 12:33:17.672 [INF] HSWC: Restoring in-memory circuit state from disk
2020-11-27 12:33:17.672 [INF] HSWC: Payment circuits loaded: num_pending=0, num_open=0
2020-11-27 12:33:17.672 [INF] HSWC: Trimming open circuits for chan_id=219599:1:0, start_htlc_id=0
2020-11-27 12:33:17.675 [DBG] CRTR: Instantiating mission control with config: PenaltyHalfLife=1h0m0s, AprioriHopProbability=0.6, AprioriWeight=0.5
2020-11-27 12:33:17.675 [DBG] CRTR: Mission control state reconstruction started
2020-11-27 12:33:17.675 [DBG] CRTR: Mission control state reconstruction finished: n=0, time=4.853µs
2020-11-27 12:33:17.675 [DBG] SRVR: Instantiating payment session source with config: PaymentAttemptPenalty=100, MinRouteProbability=0.01
2020-11-27 12:33:17.687 [DBG] CHBU: Crafting backup for ChannelPoint(9c37bf625df0023f47bf5221e4e7e58c486a3730e11df9b91dfface62f148949:0)
2020-11-27 12:33:17.687 [INF] LTND: Channel backup proxy channel notifier starting
2020-11-27 12:33:17.687 [INF] ATPL: Instantiating autopilot with active=false, max_channels=5, allocat [...]

2020-11-27 12:40 UTC, raladev requested changes
Above

2020-11-27 19:25 UTC, raladev commented
Steps:
1. `bash xud.sh -b pwd2`
2. create wallet, wait for channels (if u have no, i used old env)
3. `changepass` ->set new pass
4. down (stop and remove all containers)
5. `bash xud.sh -b pwd2` - start env again -> create new containers

Actual result:

`The following wallets could not be unlocked: BTC, LTC`  (but it was unlocked, i checked it directly. Just xud cant detect lnd, maybe because of macaroon update)
![Screenshot from 2020-11-27 22-19-48](https://user-images.githubusercontent.com/29906866/100479353-009cc580-30ff-11eb-94d6-9d86313d5743.png)
![Screenshot from 2020-11-27 22-19-11](https://user-images.githubusercontent.com/29906866/100479355-01cdf280-30ff-11eb-8976-8a4dfa599a2a.png)

Note:
Only after additional xud restart, status of lnd becomes to normal
![Screenshot from 2020-11-27 22-20-07](https://user-images.githubusercontent.com/29906866/100479469-6721e380-30ff-11eb-8ac7-9761856482d1.png)

2020-11-27 21:18 UTC, sangaman commented
OK this should be good to go now, it passes my tests using the `pwd2` docker branch and repeating the steps listed above. There were two more hurdles I had to overcome.

1. lnd recreates the macaroons after the password is changed. Xud therefore needs to reload the macaroons from disk after changing the password.

2. lnd does not *immediately* recreate the macaroons after responding to the `CreatePassword` call, so I had to create a file watch to wait for the admin.macaroon file to change before reloading them.

With the above concerns addressed, changing the master password plays nice with xud without needing any extra restarts.

2020-11-29 00:06 UTC, raladev reviewed
checked, works fine

>With the above concerns addressed, changing the master password plays nice with xud without needing any extra restarts.

does it mean that we need to remove `Passwords for lnd wallets will be changed the next time xud is restarted and unlocked.` row? @sangaman

2020-11-30 11:24 UTC, erkarl commented
Should we display a different error message when xud and lnd are running in `noencrypt` mode?
```
➜  xud git:(change-pass) ✗ ./bin/xucli changepass
You are changing the master password for xud and underlying wallets.
Enter old password:
Enter new password:
Re-enter password:

Error: 3 INVALID_ARGUMENT: old password is incorrect
```

2020-11-30 12:00 UTC, kilrau commented
Good catch - yes we should

2020-11-30 12:02 UTC, erkarl submitted a review, later dismissed

2020-11-30 12:03 UTC, erkarl commented
LGTM, just minor nit: <https://github.com/ExchangeUnion/xud/pull/2007#issuecomment-735727206>

2020-11-30 17:12 UTC, sangaman commented
I added a better error message when xud is in `noencrypt` mode, and I left the message in the cli about when the lnd passwords will change per our discussion earlier today. Just needs an approval and we can merge.

2020-11-30 17:24 UTC, kilrau approved these changes

2020-11-30 19:47 UTC, raladev approved these changes

2020-11-30 20:13 UTC, merged