feat(cli): cleaner removeorder output
ExchangeUnion/xud pull request #2022
Opened 2020-12-04 20:21 UTC by sangaman

This fixes a bug where fully removing an order via `RemoveOrder` would return the entire quantity of the order as the remaining quantity instead of zero. The problem was that when removing a quantity in full, we would simply delete it from our collection of orders but not modify its quantity, which is used (since #1986) for informational purposes on the rpc response.

It also tidies up the cli output a bit so as not to display zero amounts for holds or remaining quantity.

Fixes #2020

2020-12-04 20:47 UTC, erkarl submitted a review, later dismissed

2020-12-04 21:57 UTC, raladev requested changes
- [ ] would be good to change sats to user values
```
simnet > removeorder 1 0.1
Order 1 partially removed, 90000000 LTC remaining quantity
simnet > removeorder 1 0.8
Order 1 partially removed, 10000000 LTC remaining quantity
```

2020-12-05 15:02 UTC, sangaman commented
@raladev thanks for catching, can you check again?

2020-12-05 16:34 UTC, erkarl approved these changes

2020-12-05 16:55 UTC, kilrau approved these changes

2020-12-05 18:17 UTC, raladev approved these changes

2020-12-05 18:17 UTC, merged